/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/room2.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-4.212, 1.751, 1.615]} scale={[0.728, 0.05, 1.958]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials["hot coffee cup"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.PC_Glow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={nodes.Cube_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4.geometry}
          material={materials.pencils}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_5.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_6.geometry}
          material={materials.teller}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_7.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_8.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_9.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_10.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_11.geometry}
          material={materials["Material.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_12.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_13.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_14.geometry}
          material={materials.cards}
        />
      </group>
      <group
        position={[-4.042, 0.616, 2.58]}
        rotation={[0.031, 0, 0]}
        scale={0.001}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arceus001.geometry}
          material={materials.Material__22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arceus001_1.geometry}
          material={materials.Material__23}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arceus001_2.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arceus001_3.geometry}
          material={materials.Material__177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arceus001_4.geometry}
          material={materials.Material__178}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arceus001_5.geometry}
          material={materials.Material__179}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arceus001_6.geometry}
          material={materials["Material #190"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arceus001_7.geometry}
          material={materials["Material #191"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arceus001_8.geometry}
          material={materials["Material #192"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arceus001_9.geometry}
          material={materials["Material #193"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/room2.gltf");
