/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ..\assets\room2_gltf-transformed.glb 
*/


import { useGLTF } from '@react-three/drei'

export function ModelTransformed(props) {
  const { nodes, materials } = useGLTF('src/assets/room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-4.212, 1.751, 1.615]} scale={[0.728, 0.05, 1.958]}>
        <mesh geometry={nodes.Cube.geometry} material={materials['hot coffee cup']} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.PC_Glow} />
        <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.pencils} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube_5.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cube_6.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Cube_7.geometry} material={materials.cards} />
        <mesh geometry={nodes.Cube_8.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_9.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube_10.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[-4.042, 0.616, 2.58]} rotation={[0.031, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Arceus001.geometry} material={materials.Material__22} />
        <mesh geometry={nodes.Arceus001_1.geometry} material={materials.Material__23} />
        <mesh geometry={nodes.Arceus001_2.geometry} material={materials.Material__177} />
        <mesh geometry={nodes.Arceus001_3.geometry} material={materials.Material__178} />
        <mesh geometry={nodes.Arceus001_4.geometry} material={materials.Material__179} />
        <mesh geometry={nodes.Arceus001_5.geometry} material={materials['Material #190']} />
        <mesh geometry={nodes.Arceus001_6.geometry} material={materials['Material #191']} />
        <mesh geometry={nodes.Arceus001_7.geometry} material={materials['Material #192']} />
        <mesh geometry={nodes.Arceus001_8.geometry} material={materials['Material #193']} />
      </group>
    </group>
  )
}

useGLTF.preload('src/assets/room-transformed.glb')
